blank_issues_enabled: false
contact_links:
  - name: ğŸ“– æ–‡æ¡£
    url: https://www.hivechat.net/zh/docs
    about: é¦–å…ˆæŸ¥çœ‹é¡¹ç›®æ–‡æ¡£
  - name: ğŸ” å®‰å…¨æ¼æ´
    url: https://github.com/HiveNexus/HiveChat/security/advisories/new
    about: ç§ä¸‹æŠ¥å‘Šå®‰å…¨æ¼æ´
